// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaNTLdGQ_a3GnNW8LcAdQuUq4cE-xXb3o',
    appId: '1:387542839332:web:ee2cc516356f7abc44a8b1',
    messagingSenderId: '387542839332',
    projectId: 'eternal-sylph-387408',
    authDomain: 'eternal-sylph-387408.firebaseapp.com',
    storageBucket: 'eternal-sylph-387408.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUhFa5V-IiID8Th3uQHzyEUuKqKMUsFQk',
    appId: '1:387542839332:android:78775ea202f2d41a44a8b1',
    messagingSenderId: '387542839332',
    projectId: 'eternal-sylph-387408',
    storageBucket: 'eternal-sylph-387408.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVEhpkk6flYHdYpO3H0Ev-FYnwk-p69SY',
    appId: '1:387542839332:ios:34f3fa621c00c0ec44a8b1',
    messagingSenderId: '387542839332',
    projectId: 'eternal-sylph-387408',
    storageBucket: 'eternal-sylph-387408.appspot.com',
    iosBundleId: 'com.mobile.gdsc.aeye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVEhpkk6flYHdYpO3H0Ev-FYnwk-p69SY',
    appId: '1:387542839332:ios:34f3fa621c00c0ec44a8b1',
    messagingSenderId: '387542839332',
    projectId: 'eternal-sylph-387408',
    storageBucket: 'eternal-sylph-387408.appspot.com',
    iosBundleId: 'com.mobile.gdsc.aeye',
  );
}
