// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoeqAv7FGYNmWvIdtmkvzCzCSsgodDObc',
    appId: '1:340659862944:web:efc3ad0ad913ef46a978c5',
    messagingSenderId: '340659862944',
    projectId: 'a-eye-fcm',
    authDomain: 'a-eye-fcm.firebaseapp.com',
    storageBucket: 'a-eye-fcm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQnXX5JRQelui6MCaTzMfBt1nFj3fwZOQ',
    appId: '1:340659862944:android:5677a075c1d22ac0a978c5',
    messagingSenderId: '340659862944',
    projectId: 'a-eye-fcm',
    storageBucket: 'a-eye-fcm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5ktMbRZDL6AMr6z0w74100JDOuo1Nx-0',
    appId: '1:340659862944:ios:d0a103eaf59148dda978c5',
    messagingSenderId: '340659862944',
    projectId: 'a-eye-fcm',
    storageBucket: 'a-eye-fcm.appspot.com',
    androidClientId:
        '340659862944-l2s30f7hqghuv9acc8gj73cfmghglmrt.apps.googleusercontent.com',
    iosClientId:
        '340659862944-65qojuu06nfbdh63637ruvh1ff4ds4ca.apps.googleusercontent.com',
    iosBundleId: 'com.mobile.gdsc.aeye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5ktMbRZDL6AMr6z0w74100JDOuo1Nx-0',
    appId: '1:340659862944:ios:d0a103eaf59148dda978c5',
    messagingSenderId: '340659862944',
    projectId: 'a-eye-fcm',
    storageBucket: 'a-eye-fcm.appspot.com',
    androidClientId:
        '340659862944-l2s30f7hqghuv9acc8gj73cfmghglmrt.apps.googleusercontent.com',
    iosClientId:
        '340659862944-65qojuu06nfbdh63637ruvh1ff4ds4ca.apps.googleusercontent.com',
    iosBundleId: 'com.mobile.gdsc.aeye',
  );
}
