// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA-RLAw2t4T_h4-a5rcYQ5hNJL1WeLV90',
    appId: '1:330734716432:web:4e6e0d35227293c1e02c95',
    messagingSenderId: '330734716432',
    projectId: 'a-eye-fcm-ea7a0',
    authDomain: 'a-eye-fcm-ea7a0.firebaseapp.com',
    storageBucket: 'a-eye-fcm-ea7a0.appspot.com',
    measurementId: 'G-LK6MC79B8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2_Ab4D6m1W49EKmJsTPEF7hfAcGtyNHc',
    appId: '1:330734716432:android:c38ea97bb6ed16dae02c95',
    messagingSenderId: '330734716432',
    projectId: 'a-eye-fcm-ea7a0',
    storageBucket: 'a-eye-fcm-ea7a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZX8W7HpH1Wr4qVAQUwq4gJuDALjdoGas',
    appId: '1:330734716432:ios:27cbaab8ebc15866e02c95',
    messagingSenderId: '330734716432',
    projectId: 'a-eye-fcm-ea7a0',
    storageBucket: 'a-eye-fcm-ea7a0.appspot.com',
    iosClientId: '330734716432-v4no2kegbecjs6p5nf4fb7ef1rvjk8lg.apps.googleusercontent.com',
    iosBundleId: 'com.mobile.gdsc.aeye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZX8W7HpH1Wr4qVAQUwq4gJuDALjdoGas',
    appId: '1:330734716432:ios:27cbaab8ebc15866e02c95',
    messagingSenderId: '330734716432',
    projectId: 'a-eye-fcm-ea7a0',
    storageBucket: 'a-eye-fcm-ea7a0.appspot.com',
    iosClientId: '330734716432-v4no2kegbecjs6p5nf4fb7ef1rvjk8lg.apps.googleusercontent.com',
    iosBundleId: 'com.mobile.gdsc.aeye',
  );
}
